services:
  ucondo-challenge.api:
    image: ${DOCKER_REGISTRY-}ucondochallengeapi
    build:
      context: .
      dockerfile: src/ucondo-challenge.api/Dockerfile
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: