services:
  ucondo-challenge.api:
    image: ${DOCKER_REGISTRY-}ucondochallengeapi
    build:
      context: .
      dockerfile: src/ucondo-challenge.api/Dockerfile
  db:
    image: postgres
  redis:
    image: redis:latest    

volumes:
  db_data:
  redis_data:  